name: myenv
channels:
  - pip
  - my-channel
dependencies:
  - python=3.8
  - pandas
  - numpy
  - matplotlib
  - requests
  - ipywidgets
  - plotnine
  - pycountry
  - flagpy
  - re
  - urllib
  - html2image
  - datetime
